name: SWE.TECH
favicon: null
layout_spectrum: 0.762226
typography_spectrum: 0.6467116
title: SWE.TECH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0D0C04'
    - '#F2F9FB'
    - '#A3BDCF'
    - '#A34B2F'
    - '#E9CF65'
  brandStrength: 0.7892074
  lightness: 0.2074199
  saturation: 0.6618887
  rhythmicContrast: 0.7925801
purpose: []
